# Generated by Django 3.2.6 on 2021-09-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210901_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='django', max_length=200),
            preserve_default=False,
        ),
    ]
